### ISSUE TITLE
Access to mysql with SSL

### ISSUE THREAD

**Issue by kenjreno** [pschiffe/docker-pdns#82] opened 2022-06-01 19:46 UTC
Would like to see a way to enable SSL for mysql. There is an option in PowerDNS to allow this 
gmysql-ssl=yes

When adding PDNS_gmysql_ssl=yes as a environment filter, the docker-entry script will not proceed as it's attempting to access mysql without a '--ssl' option then sitting in a loop waiting for a connection.

**Comment by pschiffe** [comment] 2022-06-02 12:49
Could you verify the `/etc/pdns/pdns.conf` file inside of the container to check whether the config is as intended?

**Comment by kenjreno** [comment] 2022-06-02 13:44
I'm getting the error message in the logs:
ERROR 1045 (28000): Access denied for user 'pdns'@'*******************' (using password: YES)

MySQL is unavailable - sleeping

Contents of the pdns.conf are the generic version as the docker-compose.sh script can not get past the database checking to produce the file. 

(This is just the sniplet of the first few lines)
 [root@pdns /]# cat /etc/pdns/pdns.conf 
# Autogenerated configuration file template

#################################
# ignore-unknown-settings       Configuration settings to ignore if they are unknown
#
# ignore-unknown-settings=

I have PowerDNS running correctly in a TrueNAS jail, but looking to replicate it and migrate this away to a docker container using the same configuration that I currently have setup.

**Comment by pschiffe** [comment] 2022-06-02 15:00
Ah, I understand now. The mysql check command doesn't work b/c it doesn't support SSL. Do you think you could update the command in a similar fashion as here: https://github.com/pschiffe/docker-pdns/blob/master/pdns/docker-entrypoint.sh#L27 - add an if check and update the `EXTRA` var if SSL is required? I don't have such setup, so cannot test it.

**Comment by kenjreno** [comment] 2022-06-02 18:07
I added this as a check and it now gets past the sql error and created the correct pdns.conf template file.

```
# SSL Check
if [ "${PDNS_gmysql_ssl}" != "" ]; then
    EXTRA="${EXTRA} --ssl"
fi

# Password Auth
if [ "${PDNS_gmysql_password}" != "" ]; then
    EXTRA="${EXTRA} -p${PDNS_gmysql_password}"
fi

# Allow socket connections
if [ "${PDNS_gmysql_socket:-}" != "" ]; then
    export PDNS_gmysql_host="localhost"
    EXTRA="${EXTRA} --socket=${PDNS_gmysql_socket}"
fi
```
I don't have an environment built yet to build this to test this fullly end to end.

**Comment by pschiffe** [comment] 2022-06-02 18:26
If you are able to test this properly, I would love to accept your PR :)

**Comment by pschiffe** [comment] 2023-01-13 22:22
I'm closing this as it's tricky. You also need to configure cert and key on the client, so the communication is really secure, and I think this is out of scope for this project.

**Closed by pschiffe** 2023-01-13 22:22 UTC
